apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.container.port }}
  selector:
    app: postgres
    stage: {{ .Values.backend.stage }}
